# Generated by Django 5.2.1 on 2025-06-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, unique=True, verbose_name='Texto do comentário')),
                ('points', models.IntegerField(default=0, verbose_name='Pontos (likes + duplicatas)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
