# Generated by Django 5.2.1 on 2025-06-05 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
