# Generated by Django 5.2.1 on 2025-06-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
