# Generated by Django 5.2.1 on 2025-06-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_alter_comentario_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='liked',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(),
        ),
    ]
